title: Ben's Blog
author:
  name: Ben Porter
  email: 'joe@test.com'
blog:
  route: ''
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
taxonomies: [category,tag,month]
redirects:
    /changelog:
routes:
    /something/else:
    /another/one/(.*): 
